<a href="https://colab.research.google.com/github/sheldon-o/deep-learnig/blob/main/image_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
import time


In [ ]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("vectorized vesrion: "+str(1000*(toc-tic))+"ms")

vectorized vesrion: 1.4615058898925781ms


In [ ]:
c=0
tic=time.time()
for i in range(1000000):
  c+=a[i]*b[i]
toc=time.time()
print("non vectorized version: "+str(1000*(toc-tic))+"ms")

non vectorized version: 602.9853820800781ms


In [10]:
#broadcasting
#
a=np.array([[1,53,24,98],
            [2,33,51,9],
            [3,12,22,45],
            [4,3,6,9]])
cal=a.sum(axis=0)
print(cal)


[ 10 101 103 161]


In [11]:
percentage=100*a/cal
print(percentage)

[[10.         52.47524752 23.30097087 60.86956522]
 [20.         32.67326733 49.51456311  5.59006211]
 [30.         11.88118812 21.3592233  27.95031056]
 [40.          2.97029703  5.82524272  5.59006211]]


In [16]:
a=np.random.randn(1,100)
print(a)
print(a.shape)

[[-0.18241717 -0.7805281  -0.14737432 -0.14967908  0.00602003 -1.18277485
  -0.71348131 -2.56101196  2.71360447 -0.55671945  0.31203832 -0.69374998
   1.17713194 -0.47042372 -0.10980563  0.32898683 -0.2846399   0.51027367
   1.67056752  1.10029144 -1.17397844  0.6124595  -0.49658729 -0.36559202
  -0.71777097  0.12543393  1.70152046 -0.59736379  1.49874621 -0.29564006
   0.41595537 -1.05611491  0.27977481 -0.28387985 -0.07684986 -0.87881063
  -1.27987834 -0.1034913  -0.14430781 -0.39330856  1.18433228  0.40733317
  -0.77232822 -2.44390195 -1.900931   -0.0538436   0.26362724  1.02168395
   0.88127929  0.68689467 -0.15712068  0.1640778  -2.14974886 -0.74867979
   0.70114422 -0.02013375 -0.65082739  4.15626688  0.2204357  -0.77801465
  -0.94270074 -1.04488117 -1.32079709 -0.8298888  -0.67946241 -0.48169489
   0.43273125 -2.46954437  0.02916226 -0.24470796  1.47503656 -1.14619095
   0.46213138 -1.02191538 -0.24927156  2.20224155  0.86012208 -0.59025939
  -1.71514916  0.26624056 -0.58859602 

In [21]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b

In [22]:
print(c)
print(c.shape)

[[ 1.03209336  0.18516764  0.17149169]
 [-0.05395872 -0.16392678  0.10256806]
 [-0.07107236  0.43497729 -0.37866531]]
(3, 3)


In [24]:
print(a)
print(b)
print(c)

[[-2.40389456 -0.43128219 -0.39942892]
 [-0.2205351  -0.66998635  0.41920667]
 [ 0.17168406 -1.05074134  0.9147128 ]]
[[-0.42934219]
 [ 0.24467183]
 [-0.4139718 ]]
[[ 1.03209336  0.18516764  0.17149169]
 [-0.05395872 -0.16392678  0.10256806]
 [-0.07107236  0.43497729 -0.37866531]]


In [36]:
a=np.array([[[1],[2]],
           [[2],[3]]])
b=np.array([[2,3],
            [4,5]])
c=a*b
print(c)
c.shape

[[[ 2  3]
  [ 8 10]]

 [[ 4  6]
  [12 15]]]


(2, 2, 2)

In [27]:
a=np.random.randn(15,8)
b=np.random.randn(8,13)
c=np.dot(a,b)
print(c.shape)

(15, 13)


#image  vectorization



In [34]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]],
                  [[ 0.60659855,  0.00533165],
                  [ 0.10820313,  0.49978937],
                  [ 0.34144279,  0.94630077]]])
print(t_image.shape)
a=np.array([
            [1,2],
])

(4, 3, 2)


In [33]:
new=t_image.reshape(t_image.shape[0]*t_image.shape[1]*t_image.shape[2],1)
print(new.shape)


(18, 1)
